FROM python:3.9-slim

WORKDIR /app

# Install dependencies separately to leverage Docker caching
COPY node_requirements.txt .
RUN pip install --no-cache-dir -r node_requirements.txt

# Copy the server script
COPY node.py .

# Run the Flask API when the container starts
CMD ["python", "node.py"]
